/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Crash Reporter API
 * API for receiving and managing crash reports.
 * OpenAPI spec version: 0.1.0
 */
export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type InstanceCreateNotes = string | null;

export interface InstanceCreate {
  project_id: string;
  notes?: InstanceCreateNotes;
}

export interface InstanceCreateResponse {
  instance_uuid: string;
  token: string;
}

export interface InstanceOut {
  uuid: string;
  project_uuid: string;
  notes: string;
}

export interface InstanceQueryResponse {
  items: InstanceOut[];
  total: number;
  page: number;
  resultsperpage: number;
}

export interface InstanceUpdate {
  notes: string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface ProjectCreate {
  /** @pattern ^[a-z0-9_-]+$ */
  project_id: string;
  name: string;
}

export type ProjectOutStats = ProjectStats | null;

export interface ProjectOut {
  uuid: string;
  project_id: string;
  name: string;
  stats?: ProjectOutStats;
}

export interface ProjectQueryResponse {
  items: ProjectOut[];
  total: number;
  page: number;
  resultsperpage: number;
}

export interface ProjectStats {
  instances: number;
  day: number;
  week: number;
  total: number;
}

export type ProjectUpdateProjectId = string | null;

export type ProjectUpdateName = string | null;

export interface ProjectUpdate {
  project_id?: ProjectUpdateProjectId;
  name?: ProjectUpdateName;
}

export type ReportCreateMetadata = { [key: string]: unknown };

export interface ReportCreate {
  instance_uuid: string;
  /** @pattern ^(low|medium|high|critical)$ */
  severity: string;
  metadata?: ReportCreateMetadata;
}

export type ReportOutMetadata = { [key: string]: unknown };

export interface ReportOut {
  uuid: string;
  project_uuid: string;
  instance_uuid: string;
  timestamp: string;
  severity: string;
  metadata: ReportOutMetadata;
}

export interface ReportQueryResponse {
  items: ReportOut[];
  total: number;
  page: number;
  resultsperpage: number;
}

export type ReportUpdateMetadata = { [key: string]: unknown };

export interface ReportUpdate {
  metadata?: ReportUpdateMetadata;
}

export interface TokenResponse {
  access_token: string;
  token_type?: string;
  expires_in_seconds: number;
}

export interface UserCreate {
  username: string;
  password: string;
}

export interface UserOut {
  uuid: string;
  username: string;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export type QueryProjectsApiV1ProjectQueryGetParams = {
uuids?: string[] | null;
project_ids?: string[] | null;
name?: string | null;
page?: number;
resultsperpage?: number;
include_stats?: boolean;
sort_by?: string | null;
sort_dir?: string;
};

export type QueryInstancesApiV1InstanceQueryGetParams = {
uuids?: string[] | null;
project_uuids?: string[] | null;
project_ids?: string[] | null;
page?: number;
resultsperpage?: number;
sort_by?: string | null;
sort_dir?: string;
};

export type QueryReportsApiV1ReportQueryGetParams = {
uuids?: string[] | null;
instance_uuids?: string[] | null;
project_ids?: string[] | null;
project_uuids?: string[] | null;
project_name?: string | null;
severity?: string[] | null;
page?: number;
resultsperpage?: number;
sort_by?: string | null;
sort_dir?: string;
};

