/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Crash Reporter API
 * API for receiving and managing crash reports.
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  InstanceCreate,
  InstanceCreateResponse,
  InstanceOut,
  InstanceQueryResponse,
  InstanceUpdate,
  LoginRequest,
  ProjectCreate,
  ProjectOut,
  ProjectQueryResponse,
  ProjectUpdate,
  QueryInstancesApiV1InstanceQueryGetParams,
  QueryProjectsApiV1ProjectQueryGetParams,
  QueryReportsApiV1ReportQueryGetParams,
  ReportCreate,
  ReportOut,
  ReportQueryResponse,
  ReportUpdate,
  TokenResponse,
  UserCreate,
  UserOut
} from '../backend.schemas';




  export const getDefault = () => {
/**
 * @summary Login
 */
const loginApiV1LoginPost = <TData = AxiosResponse<TokenResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/login`,
      loginRequest,options
    );
  }
/**
 * @summary Create User
 */
const createUserApiV1UserPost = <TData = AxiosResponse<UserOut>>(
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/user`,
      userCreate,options
    );
  }
/**
 * @summary Create Project
 */
const createProjectApiV1ProjectPost = <TData = AxiosResponse<ProjectOut>>(
    projectCreate: ProjectCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/project`,
      projectCreate,options
    );
  }
/**
 * @summary Query Projects
 */
const queryProjectsApiV1ProjectQueryGet = <TData = AxiosResponse<ProjectQueryResponse>>(
    params?: QueryProjectsApiV1ProjectQueryGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/project/query`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Get Project
 */
const getProjectApiV1ProjectUuidGet = <TData = AxiosResponse<ProjectOut>>(
    uuid: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/project/${uuid}`,options
    );
  }
/**
 * @summary Update Project
 */
const updateProjectApiV1ProjectUuidPatch = <TData = AxiosResponse<ProjectOut>>(
    uuid: string,
    projectUpdate: ProjectUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/project/${uuid}`,
      projectUpdate,options
    );
  }
/**
 * @summary Update Project
 */
const updateProjectApiV1ProjectUuidPut = <TData = AxiosResponse<ProjectOut>>(
    uuid: string,
    projectUpdate: ProjectUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/project/${uuid}`,
      projectUpdate,options
    );
  }
/**
 * @summary Delete Project
 */
const deleteProjectApiV1ProjectUuidDelete = <TData = AxiosResponse<unknown>>(
    uuid: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/project/${uuid}`,options
    );
  }
/**
 * @summary Create Instance
 */
const createInstanceApiV1InstancePost = <TData = AxiosResponse<InstanceCreateResponse>>(
    instanceCreate: InstanceCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/instance`,
      instanceCreate,options
    );
  }
/**
 * @summary Query Instances
 */
const queryInstancesApiV1InstanceQueryGet = <TData = AxiosResponse<InstanceQueryResponse>>(
    params?: QueryInstancesApiV1InstanceQueryGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/instance/query`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Get Instance
 */
const getInstanceApiV1InstanceUuidGet = <TData = AxiosResponse<InstanceOut>>(
    uuid: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/instance/${uuid}`,options
    );
  }
/**
 * @summary Update Instance
 */
const updateInstanceApiV1InstanceUuidPatch = <TData = AxiosResponse<InstanceOut>>(
    uuid: string,
    instanceUpdate: InstanceUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/instance/${uuid}`,
      instanceUpdate,options
    );
  }
/**
 * @summary Update Instance
 */
const updateInstanceApiV1InstanceUuidPut = <TData = AxiosResponse<InstanceOut>>(
    uuid: string,
    instanceUpdate: InstanceUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/instance/${uuid}`,
      instanceUpdate,options
    );
  }
/**
 * @summary Delete Instance
 */
const deleteInstanceApiV1InstanceUuidDelete = <TData = AxiosResponse<unknown>>(
    uuid: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/instance/${uuid}`,options
    );
  }
/**
 * @summary Create Report
 */
const createReportApiV1ReportPost = <TData = AxiosResponse<ReportOut>>(
    reportCreate: ReportCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/report`,
      reportCreate,options
    );
  }
/**
 * @summary Query Reports
 */
const queryReportsApiV1ReportQueryGet = <TData = AxiosResponse<ReportQueryResponse>>(
    params?: QueryReportsApiV1ReportQueryGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/report/query`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Get Report
 */
const getReportApiV1ReportUuidGet = <TData = AxiosResponse<ReportOut>>(
    uuid: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/report/${uuid}`,options
    );
  }
/**
 * @summary Update Report
 */
const updateReportApiV1ReportUuidPatch = <TData = AxiosResponse<ReportOut>>(
    uuid: string,
    reportUpdate: ReportUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/report/${uuid}`,
      reportUpdate,options
    );
  }
/**
 * @summary Update Report
 */
const updateReportApiV1ReportUuidPut = <TData = AxiosResponse<ReportOut>>(
    uuid: string,
    reportUpdate: ReportUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/report/${uuid}`,
      reportUpdate,options
    );
  }
/**
 * @summary Delete Report
 */
const deleteReportApiV1ReportUuidDelete = <TData = AxiosResponse<unknown>>(
    uuid: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/report/${uuid}`,options
    );
  }
return {}};
